groups:
  - name: custom_rules
    rules:
      - record: node_memory_MemFree_percent
        expr: 100 - (100 * node_memory_MemFree_bytes / node_memory_MemTotal_bytes)

      - record: node_filesystem_free_percent
        expr: 100 * node_filesystem_free_bytes{fstype=~"ext4|vfat"} / node_filesystem_size_bytes{fstype=~"ext4|vfat"}

      - record: node_filesystem_used_percent
        expr: 100 * ((node_filesystem_size_bytes{fstype=~"ext4|vfat"} - node_filesystem_free_bytes{fstype=~"ext4|vfat"} )/ node_filesystem_size_bytes{fstype=~"ext4|vfat"})

      - record: node_network_receive_rate_1m
        expr: rate(node_network_receive_bytes_total[1m])

      - record: node_network_transmit_rate_1m
        expr: rate(node_network_transmit_bytes_total[1m])

      - record: node_cpu_seconds_system_rate_1m
        expr: rate(node_cpu_seconds_total{mode="system"}[1m])

      - record: node_cpu_seconds_system_rate_5m
        expr: rate(node_cpu_seconds_total{mode="system"}[5m])

      - record: node_cpu_seconds_user_rate_1m
        expr: rate(node_cpu_seconds_total{mode="user"}[1m])

      - record: node_cpu_seconds_user_rate_5m
        expr: rate(node_cpu_seconds_total{mode="user"}[5m])

